name: matplotlib-aximgcache (pip install)
on: [push, pull_request]

jobs:
  test:
    name: Test pip install python ${{ matrix.python-version }} on ${{ matrix.os }}

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.7]
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install .[test]
      - name: Test package with pytest (including notebooks)
        run: |
          python -m pytest --nbval-lax --current-env
